name: ipe
version: 7.2.7
summary: Ipe http://ipe.otfried.org/
description: Drawing editor for creating figures in PDF format.
  Ipe supports making small figures for inclusion into LaTeX
  documents as well as making multi-page PDF presentations.
  Ipe's main features are
    * Entry of text as LaTeX source code. This makes it easy to enter
      mathematical expressions, and to reuse the LaTeX-macros of the main
      document.  In the display text is displayed as it will appear in
      the figure.
    * Produces pure Postscript/PDF, including the text. Ipe converts the
      LaTeX-source to PDF or Postscript when the file is saved.
    * It is easy to align objects with respect to each other (for
      instance, to place a point on the intersection of two lines, or to
      draw a circle through three given points) using various snapping
      modes.
    * Users can provide ipelets (Ipe plug-ins) to add functionality to
      Ipe.  This way, Ipe can be extended for each task at hand.
    * The text model is based on Unicode, and has been tested with Korean,
      Chinese, and Japanese.

grade: devel
confinement: strict

parts:
  ipe:
    source: https://dl.bintray.com/otfried/generic/ipe/7.2/ipe-7.2.7-src.tar.gz
    source-subdir: src
    plugin: make
    make-parameters:
      - IPESNAPCRAFT=1
      - IPEQVORONOI=1
      - QT_SELECT=5
      - IPESTRICT=1
    build-packages:
      - libcairo2-dev
      - libfreetype6-dev
      - liblua5.3-dev
      - libjpeg8-dev
      - libpng12-dev
      - make
      - qtbase5-dev
      - qtbase5-dev-tools
      - zlib1g-dev
      - libqhull-dev
    after: [desktop-qt5]

  wrapper:
    plugin: dump
    source: ./wrapper
    organize:
      wrapper.sh: bin/wrapper.sh
      tlmgr.sh: bin/tlmgr

  texlive:
    plugin: texlive
    source: http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    build-packages:
      - wget
    prime:
      - -texlive/texmf-dist/doc
      - -texlive/texmf-dist/source
      - -texlive/texmf-dist/tex/context
      - -texlive/texmf-dist/tex/plain
      - -texlive/texmf-var/web2c/luatex/dvi*
      - -texlive/texmf-var/web2c/luatex/luatex.*
      - -texlive/texmf-var/web2c/luajittex/
      - -texlive/texmf-var/web2c/tex/
      - -texlive/texmf-var/web2c/metafont
      - -texlive/texmf-var/web2c/pdftex/etex.*
      - -texlive/texmf-var/web2c/pdftex/latex.*
      - -texlive/texmf-var/web2c/pdftex/mptopdf.*
      - -texlive/texmf-var/web2c/pdftex/pdfetex.*
      - -texlive/texmf-var/web2c/pdftex/pdftex.*
      - -texlive/bin/x86_64-linux/xdvi*
      - -texlive/bin/x86_64-linux/luajittex
      - -texlive/bin/x86_64-linux/g*
      - -texlive/bin/x86_64-linux/dvi*

apps:
  ipe:
    command: desktop-launch wrapper.sh ipe
    plugs: [x11, home]

  ipetoipe:
    command: wrapper.sh ipetoipe
    plugs: [home]

  ipeextract:
    command: wrapper.sh ipeextract
    plugs: [home]

  iperender:
    command: wrapper.sh iperender
    plugs: [home]

  ipescript:
    command: wrapper.sh ipescript
    plugs: [home]

  ipe6upgrade:
    command: wrapper.sh ipe6upgrade
    plugs: [home]

  pdflatex:
    command: wrapper.sh pdflatex
    plugs: [home]

  lualatex:
    command: wrapper.sh lualatex
    plugs: [home]

  bibtex:
    command: wrapper.sh bibtex
    plugs: [home]

  kpsewhich:
    command: wrapper.sh kpsewhich
    plugs: [home]

  sh:
    command: wrapper.sh sh
    plugs: [home]
